name: Render Spring POC hook example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - run: curl ${{secrets.RENDER_DEPLOY_HOOK}}
